server:
  port: 8080
spring:
  application:
    name: Sonarqube-Project
#  datasource:
#    username: root
#    password: ola24oluwa
#    url: jdbc:mysql://localhost:3306/simple_book
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      use-new-id-generator-mappings: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
